# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F8_Xky4K7nyVy2eCrTnSeZq5554LSU4n
"""

class Employee:
   def __init__(self, basic_salary=500):
     self.basic_salary=basic_salary
class chef(Employee):
   def __init__(self,hourly_wage,hours,days):
         super().__init__(550)
         self.hourly_wage=hourly_wage
         self.hours=hours
         self.days=days
   def get_monthly_income(self):
          return self.hourly_wage * self.hours * self.days + self.basic_salary
class weighter(Employee):
   def __init__(self,monthly_salary,tips):
          super().__init__(600)
          self.monthly_salary = monthly_salary
          self.tips = tips
   def get_monthly_income(self):
         return self.monthly_salary + self.tips * 0.5 + self.basic_salary
class cleaner(Employee):
   def __init__(self,monthly_salary, extra_hours,extra_hour_wage):
         super().__init__()
         self.monthly_salary = monthly_salary
         self.extra_hours = extra_hours
         self.extra_hour_wage = extra_hour_wage
   def get_monthly_income(self):
        return self.monthly_salary + self.extra_hours * self.extra_hour_wage  + self.basic_salary
print("****************SALARY MANAGEMENT********************")

steve = chef(200,6,22)
steve_salary = steve.get_monthly_income()
print("salary for chef steve : ",steve_salary)
p

ronny = weighter(7500, 200)
ronny_salary = ronny.get_monthly_income()
print("salary for weighter ronny : ",ronny_salary)

alex = cleaner(3500, 15, 20)
alex_salary = alex.get_monthly_income()
print("salary for cleaner alex : ",alex_salary)


income = int(input("enter the income by restuarent : "))
profit = income - steve_salary - ronny_salary - alex_salary
print("profit for the restuarent : ",profit )

